site_name: SN-Graph

theme:
  name: "material"

repo_url: https://github.com/alexandrainst/sn-graph

plugins:
- mkdocstrings

nav:
- Introduction: index.md
- Installation and basic usage: installation.md
- API Reference: reference.md
